* 智能推荐
- 以“客户需求”为导向的，是给客户带来价值的服务, 提高商品的活力、挖掘消费者的购买力、促进最大化销售
- 基于关联规则的购物篮推荐,其建模理念为：物品被同时购买的模式反映了客户的需求模式
- *适用场景* ：无需个性化定制的场景；有销售记录的产品，向老客户推荐；套餐设计与产品摆放。
** 运行要求:
#+begin_src bash
streamlit run smart_sugg.py
#+end_src



** FAQ
问：什么是购物篮？主要运用在什么场景？

答：单个客户一次购买商品的综合称为一个购物篮，即某个客户本次的消费小票。常用场景：超市货架布局：互补品与互斥品；套餐设计。

问：购物篮的常用算法？

答：常用算法有

不考虑购物顺序：关联规则。购物篮分析其实就是一个因果分析。关联规则其实是一个很方便的发现两样商品关系的算法。共同提升的关系表示两者是正相关，可以作为互补品，如豆瓣酱和葱一起卖也才是最棒的。替代品的概念便是我买了这个就不用买另外一个。
考虑购物顺序：序贯模型。多在电商中使用，比如今天你将这个商品加入了购物车，过几天又将另一个商品加入了购物车，这就有了一个前后顺序。但许多实体商店因为没有实名认证，所以无法记录用户的消费顺序。

问：求出互补品与互斥品后对布局有什么用？

答：根据关联规则求出的商品间的关联关系后，可能会发现商品间存在强关联，弱关联与排斥三种关系。每种清醒有各自对应的布局方式。

- 强关联：关联度的值需要视实际情况而定，在不同的行业不同的也业态是不同的。强关联的商品彼此陈列在一起会提高双方的销售量。双向关联的商品如果陈列位置允许的话应该相关联陈列，即A产品旁边有B，B产品边上也一定会有A，比如常见的剃须膏与剃须刀，男士发油与定型梳；而对于那些单向关联的商品，只需要被关联的商品陈列在关联商品旁边就行，如大瓶可乐旁边摆纸杯，而纸杯旁边则不摆大瓶可乐，毕竟买大可乐的消费者大概率需要纸杯，而购买纸杯的顾客再购买大可乐的概率不大。
- 弱关联：关联度不高的商品，可以尝试摆在一起，然后再分析关联度是否有变化，如果关联度大幅提高，则说明原来的弱关联有可能是陈列的原因造成的。
- 排斥关系：指两个产品基本上不会出现在同一张购物小票中，这种商品尽量不要陈列在一起。

根据购物篮的信息来进行商品关联度的分析不仅仅只有如上三种关系，它们仅代表商品关联度分析的一个方面（可信度）。全面系统的商品关联分析必须有三度的概念，三度包括支持度，可信度和提升度。

支持度（Support）：支持度可以理解为物品当前流行程度。计算方式是：

支持度 = （包含物品A的记录数量） / （总的记录数量）

用上面的超市记录举例，一共有五个交易，牛奶出现在三个交易中，故而{牛奶}的支持度为3/5。{鸡蛋}的支持度是4/5。牛奶和鸡蛋同时出现的次数是2，故而{牛奶，鸡蛋}的支持度为2/5。

置信度（Confidence）：置信度是指如果购买物品A，有较大可能购买物品B。计算方式是这样：

置信度( A -> B) = （包含物品A和B的记录数量） / （包含 A 的记录数量）

举例：我们已经知道，(牛奶，鸡蛋)一起购买的次数是两次，鸡蛋的购买次数是4次。那么Confidence(牛奶->鸡蛋)的计算方式是Confidence(牛奶->鸡蛋)=2 / 4。

提升度（Lift）：提升度指当销售一个物品时，另一个物品销售率会增加多少。计算方式是：

提升度( A -> B) = 置信度( A -> B) / (支持度 A)

*   常用工具
** datafile
#+begin_src bash
#中文字体转换编码
enca -L zh_CN data/shop_data.csv
enca -L zh_CN -x UTF-8 data/shopping_data.csv
#+end_src
** podman/docker
https://vuepress.docker-practice.com/image/

Apriori 算法是一种最有影响力的挖掘布尔关联规则的频繁项集的 算法，它是由Rakesh Agrawal 和RamakrishnanSkrikant 提出的。它使用一种称作逐层搜索的迭代方法，k- 项集用于探索（k+1）- 项集。首先，找出频繁 1- 项集的集合。该集合记作L1。L1 用于找频繁2- 项集的集合 L2，而L2 用于找L2，如此下去，直到不能找到 k- 项集。每找一个 Lk 需要一次数据库扫描。为提高频繁项集逐层产生的效率，一种称作Apriori 性质的重 要性质 用于压缩搜索空间。其运行定理在于一是频繁项集的所有非空子集都必须也是频繁的，二是非频繁项集的所有父集都是非频繁的。

https://www.cnblogs.com/listenfwind/p/11395703.html
